### ISSUE TITLE
DigiByte Mobile wallet images, video and app store

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/digi-id-io#3]
I'm opening this issue to help improve the Digi-ID.io website. I've recommended the website to people for them to learn about Digi-ID open auth and my biggest concern is that they see the DigiByte mobile wallet and download the iOS/Android wallet applications. If we're trying to educate and spread awareness about Digi-ID these wallets really set us back. Imagine someone going to the website, downloads the app but it fails to sync and newer versions of Android no longer support the DigiByte mobile app, we're kind of shooting ourselves in the foot by keeping images, videos and download links for the DigiByte mobile applications on this and other websites. I don't believe anyone interested in Digi-ID would want to use the product if they downloaded the wallet and it failed to sync or was not supported for Android users.

Recommendations: 
Home page
1. Change the Image of the DigiByte mobile app to an image of Digi-ID/AntumID app.
2. Reword Access in the DigiByte App to Digi-ID open authentication
3. Update the mobile wallet download links to Digi-ID/AntumID download links
4. Digi-ID/AntumID needs to be added to Google play store

Get started/ Download an authenticator app section
1. Delete DigiByte app and download links
2. The image of Digi-ID/AntumID is incorrect the download link for Google Play doesn't work. Digi-ID/AntumID app for iOS works is good, however, its not depicted on the image. Scroll down to second image. 

(1/2 DigiByte mobile image with download links)
![Screenshot 2023-07-01 192428](https://github.com/DigiByte-Core/digi-id-io/assets/136190014/2c6b7d47-d3ce-49c2-a1e7-17072d547313)
(2/2 Get started section / Download an authenticator app) 
![Screenshot 2023-07-01 193152](https://github.com/DigiByte-Core/digi-id-io/assets/136190014/059146c7-a491-4300-be1f-e016a152a84c)

**Comment by Sbosvk** [comment]
I don't think we necessarily need to remove the image of the DigiByte Mobile app here as long as we remove all other references and links. For all intents and purposes it is just "some wallet" with Digi-ID.
